apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml
- gateway_authorizationpolicy.yaml
- deny_all_authorizationpolicy.yaml
- gateway.yaml
- x-forwarded-host.yaml

namespace: istio-system

patchesStrategicMerge:
- patches/service.yaml
- patches/remove-pdb.yaml
- patches/istio-configmap-disable-tracing.yaml

images:
- name: docker.io/istio/proxyv2
  newName: 192.168.202.201:15001/istio/proxyv2
  newTag: 1.9.6
- name: docker.io/istio/pilot
  newName: 192.168.202.201:15001/istio/pilot
  newTag: 1.9.6