apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
images:
  - name: kubeflow/training-operator
    newName: 192.168.202.201:15001/kubeflow/training-operator
    newTag: v1-e1434f6