apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  app: mxnet-operator
  app.kubernetes.io/component: mxnet
  app.kubernetes.io/name: mxnet-operator
  kustomize.component: mxnet-operator

resources:
- crd-v1.yaml

patchesStrategicMerge:
  - deployment.yaml

images:
- name: kubeflow/mxnet-operator
  newName: 192.168.202.201:15001/kubeflow/mxnet-operator
  newTag: v1.1.0