apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- cluster-local-gateway.yaml
- gateway-authorizationpolicy.yaml
- gateway.yaml

patchesStrategicMerge:
- patches/remove-pdb.yaml

images:
- name: docker.io/istio/proxyv2
  newName: 192.168.202.201:15001/istio/proxyv2
  newTag: 1.9.6