apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newName: 192.168.202.201:15001/public.ecr.aws/j1r0q0g6/training/training-operator
    newTag: "760ac1171dd30039a7363ffa03c77454bd714da5"
