apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Install Kserve in kubeflow namespace
- kserve_kubeflow.yaml
images:
  - name: kserve/kserve-controller
    newName: 192.168.202.201:15001/kserve/kserve-controller
    newTag: v0.8.0

# If you want to install both KFServing and KServe, install the
# standalone kserve manifests, to avoid conflicts with 0.6.1 KFServing.
# - kserve.yaml
# - aggregated-roles.yaml
# - kserve-runtimes.yaml
# configMapGenerator:
#   - name: kserve-config
#     namespace: kserve
#     behavior: merge
#     envs:
#     - params.env